.TH "uriel" "1" "November 2025" "uriel 1.3.9" "User Commands"

.SH NAME

.B uriel
- Yet another static website generator

.SH SYNOPSIS

.B uriel
<project-root>

.SH DESCRIPTION

Uriel is a minimalistic, stable, feature complete static site generator,
written in Python.

https://nathanrosenquist.com/uriel/

.SH OVERVIEW

Uriel is designed to create static web sites, using a combination of content
nodes and HTML templates. The results are merged into a static web site, which
can be hosted pretty much anywhere.

This man page is not a comprehensive reference. It is intended to act more
like a cheat sheet, as an additional supplement to the full documentation.

.SH USAGE

\fBuriel\fP <project-root>

If the project root is a directory that does not exist, it will be created and
initialized with new project files. Subsequent invocations of the \fBuriel\fP
command against the project root will regenerate the static files of the web
site from the project files.

.SH HEADERS

Node files support headers. You can define and reference any custom headers
you want. Some headers also have special meanings, and are interpreted
directly by \fBuriel\fP.

Some special headers can be set on any node, while others will only take
effect if they are set on the root node (\fIindex\fP).

.B All Nodes
.TS
tab(@), left, box;
l | l | l
lB | l | l.
Header@Default@Notes

Title@<inferred>@Page title
Escape-Title@true@HTML escape title
Template@default.html@Template file
Format@html@"html" or "text"
Created@@date -Is / date +%FT%T
Modified@node mtime@date -Is / date +%FT%T
Breadcrumb-Separator@&raquo;@Between breadcrumbs
Breadcrumb-Separator-Spaces@true@Spaces around separator
Flat-URL@false@Move URL path to top
Link-Prefix@<p>@For lists of links
Link-Suffix@</p>@For lists of links
Tags@@foo, bar, baz, quux
RSS-Include@false@Include node in RSS
RSS-Add-Node-Title-Header@true@Add node title to RSS
Sitemap-Include@true@Include node in sitemap
.TE

.B Root Node
.TS
tab(@), left, box;
l | l | l
lB | l | l.
Header@Default@Notes

Canonical-URL@@https://example.com
Tag-Node@@tag
RSS-URL@@/rss.xml
RSS-Title@<value of Title>@Site name
RSS-Description@@Site description
RSS-Image-URL@@/rss-icon.png
RSS-Image-Width@@32
RSS-Image-Height@@32
Sitemap-URL@@/sitemap.xml
.TE

.B Inheritance

The content nodes form a tree hierarchy, starting with the root node
(\fIindex\fP).
Generally speaking, if a header is set on a node, it will be inherited by
all downstream child nodes by default.

As an exception to this general rule, the following headers are specifically
not inherited:

.RS
.nf
.B Title
.B Created
.B Modified
.RE

To delete an inherited header from the current node:

.RS
.nf
.B -Foo: *
.RE

Set a header in child nodes, but not the current node:

.RS
.nf
.B +Foo: bar
.RE

.SH SUBSTITUTION PARAMETERS

Substitution parameters can be used in content nodes and HTML templates.

When a substitution parameter is encountered, it will be replaced with its
value during web site rendering.

.TS
tab(@), left, box;
l | l
lB | l.
Parameter@Notes

{{node:body}}@Entire node body contents
{{include:default.html}}@include:path/to/template.html
{{value:foo}}@rvalue is <lowercase-header-name>
{{value-unescaped:foo}}@rvalue is <lowercase-header-name>
{{breadcrumbs:*}}@HTML navigation breadcrumbs
{{created:%B %d, %Y}}@man strftime
{{modified:%B %d, %Y}}@man strftime
{{static-url:foo.jpg}}@a.jpg, i/a.jpg, /a.jpg
{{static-hash-url:foo.css}}@a.css, c/a.css, /a.css
{{rss:url}}@Canonical RSS URL
{{node:url}}@Node URL
{{node:name}}@Node name (e.g. foo/bar)
{{node:title}}@Node title
{{node:link}}@<a href="/node-url/">Node Title</a>
{{node-url:foo/bar}}@Node URL for the foo/bar node
{{node-name:foo/bar}}@Node name for the foo/bar node
{{node-title:foo/bar}}@Node title for the foo/bar node
{{node-link:foo/bar}}@<a href="/foo/bar/">Foo Bar</a>
{{node-list:*}}@Links to child nodes
{{tag-list:*}}@Links to relevant tags
{{soju:your_code_here()}}@See lib/soju.py
.TE

.SH PROJECT DIRECTORIES

When you create a project with \fBuriel\fP, a new project directory
is created, with the following directories inside:

.TS
tab(@), left, box;
l | l
lB | l.
Directory@Notes

templates@Templates to merge with dynamic content nodes
nodes@Dynamic content nodes to merge with templates
lib@User-defined Python code (soju.py, handlers.py)
static@Static content to copy to the web site unmodified
public@Rendered web site
.TE

.SH SEE ALSO
\fBpython3\fP(1), \fBmake\fP(1), \fBdate\fP(1), \fBstrftime\fP(3)

.SH LICENSE

Uriel is distributed under the GNU General Public License (Version 3).
See the file COPYING for details.

.SH AUTHOR

Nathan Rosenquist
