##############################################################################
# soju.py                                                                    #
##############################################################################

# The following symbols are imported using magic:
#
# import uriel
# from uriel import SojuError
# from uriel import log
# from uriel import escape

# The following variables are available to pass to functions:
#
# page
# node
# project_root
# use_canonical_url

# {{soju:node_title(node)}}
def node_title(node):
    return escape(node.get_title())

# {{soju:node_path(node)}}
def node_path(node):
    """
    Get the path of the current node.
    There is no built-in equivalent substitution parameter.

    Accepts a Node.
    
    Returns an HTML escaped string with the node path.

    """

    return escape(node.get_path())

# {{soju:node_created(node, strftime_format)}}
def node_created(node, strftime_format):
    """
    Get the time that the node was created, formatting according to the
    strftime format string.

    Accepts a Node, and an strftime format string.

    Returns an HTML escaped string with the formatted time if the
    Created header was set on this node, or an empty string otherwise.

    """

    if node.created:
        return escape(node.created.strftime(strftime_format))

    return ""

# {{soju:hello_world(node)}}
def hello_world(node):
    """
    Hello world function.

    Accepts a Node.

    Returns an HTML escaped hello world message.

    """

    return "Hello from lib/soju.py, called from " + escape(node.get_path())

# {{soju:example(page, node, project_root, use_canonical_url)}}
def example(page, node, project_root, use_canonical_url):
    """
    Example Soju function, demonstrating several things in one place.

    Accepts a page, node, project_root, and use_canonical_url.

    Returns an example string to use in the Soju documentation.

    """

    # log a message when the site builds
    log("the example() function is running now")

    # create a list of strings that we will combine and return
    lines = []

    # show the uriel version (which is referenced from the uriel module,
    # along with the string values of each argument passed to this function
    lines.append("Hello from the <b>example()</b> function!")
    lines.append("")
    lines.append("Generated by uriel version " + escape(uriel.VERSION))
    lines.append("")
    lines.append("page:              " + escape(str(page)))
    lines.append("node:              " + escape(str(node)))
    lines.append("project_root:      " + escape(project_root))
    lines.append("use_canonical_url: " + escape(str(use_canonical_url)))
    lines.append("")

    # find the node for the Uriel API documentation index
    # (the nodes/uriel/index file)
    uriel_api_doc_index_node = node.find_node_by_path("uriel/index")

    # show a link to the node
    lines.append(uriel_api_doc_index_node.get_link())

    # go through each child node under the Uriel API documentation index,
    # sorted by (title + node path). Title is not always guaranteed to
    # be unique, so the unique node path will act as a tie breaker in.
    # case any nodes have the same title.
    for child_node in sorted(uriel_api_doc_index_node.get_children(),
                             key=lambda n: n.get_title() + n.get_path()):

        lines.append("  " + child_node.get_link())

    # if you uncomment this line, it will cause an error when the site builds
    #raise SojuError("oops")

    # combine and return the lines as a string
    return "\n".join(lines)

# {{soju:get_template(node)}}
def get_template(node):
    """
    Get the template used by the given node.

    Accepts a Node.

    Returns the template used for that node.

    This could almost be handled by a simple {{value:template}} parameter.
    Except that if no template header is set, the default is used instead,
    and in that case, the {{value:template}} reference would be undefined
    and the site wouldn't build.

    This method checks to see if the header is set, and either returns
    the template header, or the default template.

    """

    if node.has_header("template"):
        return escape(node.get_header("template"))

    return escape(uriel.DEFAULT_TEMPLATE)

# {{soju:get_node_header_table(project_root, node)}}
def get_node_header_table(project_root, node):
    """
    Get an HTML table showing the headers defined on the given node.

    Accepts project_root, and a Node.

    Returns an HTML table.

    """

    # check this node directly, to see if the node file actually has
    # a definition for each header. for any headers that were
    # actually specified directly in the node file, skip all
    # inheritance checks when printing the table.
    # we already know where they came from.
    headers_defined_on_this_node = set()
    if "file" == node.get_node_type():
        isolated_node = uriel.FileNode(project_root, node.get_path())
        for header in isolated_node.get_header_keys():
            headers_defined_on_this_node.add(header)

    lines = []

    lines.append("<table>")

    lines.append("    <tr align=\"left\">")
    lines.append("        <th>Header (Lowercase)</th>")
    lines.append("        <th>Value</th>")
    lines.append("    </tr>")

    # go through each header directly defined on this node
    for header in sorted(headers_defined_on_this_node):
        # ignore internal headers used during site generation
        if header.startswith("__"):
            continue

        # get the header value
        value = node.get_header(header)

        # if this header was defined directly on this node,
        # make the header and value stand out visually
        lines.append("    <tr>")
        lines.append("        <td><b>" + escape(header) + "</b></td>")
        lines.append("        <td><b>" + escape(value) + "</b></td>")
        lines.append("    </tr>")

    # go through each inherited header on this node
    for header in node.get_header_keys():
        # ignore internal headers used during site generation
        if header.startswith("__"):
            continue

        # get the header value
        value = node.get_header(header)

        if header not in headers_defined_on_this_node:
            lines.append("    <tr>")
            lines.append("        <td>" + escape(header) + "</td>")
            lines.append("        <td>" + escape(value) + "</td>")
            lines.append("    </tr>")

    lines.append("</table>")

    return "\n".join(lines)

# {{soju:get_project_file(node)}}
def get_project_file(node):
    """
    Get a link to the node file from the project
    (or an empty string for virtual nodes).

    """

    # if this is a virtual node, it doesn't have a project file
    if "virtual" == node.get_node_type():
        return ""

    # get the node path
    path = node.get_path()

    # return a link to the source code for the node file in the project
    return \
        '<a href="https://github.com/ratherlargerobot/uriel/blob/main/documentation/nodes/' + \
        path + '">nodes/' + path + '</a>'

# {{soju:latest_year(node)}}
def latest_year(node):
    """
    Get the latest year in this or any of the child nodes.

    This is useful to show the latest copyright date for a given section of a
    web site.

    If the site has a tag index, the root node will always show the current
    year, because the tag node is a child of the root node, and tags are
    always assigned the current time when the site is built.

    """

    # traverse this and the child nodes, find all the
    # created/modified dates, and stick them in the dates set
    def __get_all_dates_in_child_nodes(node, dates):
        if node.created:
            dates.add(node.created)
        dates.add(node.modified)

        for child in node.get_children():
            __get_all_dates_in_child_nodes(child, dates)

    # call the nested function
    dates = set()
    __get_all_dates_in_child_nodes(node, dates)

    # pick the latest date out of the set
    for latest in reversed(sorted(dates)):
        return latest.strftime("%Y")

# get the uriel version number that built this site
# {{soju:uriel_version()}}
def uriel_version():
    """
    Gets the HTML escaped version of the uriel program that built this site.

    """

    return escape(str(uriel.VERSION))

# {{soju:get_hostname_from_canonical_url(node)}}
def get_hostname_from_canonical_url(node):
    """
    Get the hostname portion from the Canonical-URL, and return it.

    If the Canonical-URL header is not set, this returns "localhost".

    """

    # if we have a Canonical-URL header
    if node.has_header("canonical-url"):
        canonical_url = node.get_header("canonical-url")

        # and it looks like it contains a canonical URL
        if "://" in canonical_url:
            # get the host (and maybe :port portion)
            host_and_maybe_port = canonical_url.split("://", 1)[1]

            # return the host portion (without the port, if present)
            return host_and_maybe_port.split(":", 1)[0]

    # if all else fails
    return "localhost"

# N.B. this sort of thing isn't generally recommended on normal sites
#      this function allows demonstrating lots of different node method calls
#      from the reference section at the bottom of each page on this site
def node_method(node, method_name):
    return escape(str(eval("node." + method_name + "()")))

